version: 2.1

jobs:
  # build:
  #   working_directory: ~/circleci-python
  #   docker:
  #     - image: "circleci/python:3.9.1"
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: pip install -r backend/requirements.txt
  #     - run: 
  #         name: Building
  #         command: python3 backend/src/main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.1"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install pytest
      - run:
          name: Running tests
          command: python -m pytest

workflows:
  build_and_test:
    jobs:
      # - build
      - test
      # - test:
          # requires:
          #   - build
