version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.1"
    steps:
      - checkout
      - run: 
          name: Building
          command: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9.1"
    steps:
      - checkout
      - run:
          name: Running tests
          command: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
